### PR TITLE
B 308 fixed. <use> support now available.

### LINKED ISSUE #308: SVG problem
The attached SVG file is rendered correctly in all SVG tool and Chrome itself. However its wrong in Mr Beam UI.

Looks like the error is happening here:
Working_area.js:535:
`newSvg.bake(); // remove transforms`
however I'm not sure if it's just getting visible during the bake.

Chrome:
screenshot 2018-07-10 17 08 57

Mr Beam II:
screenshot 2018-07-10 17 10 44
[Dokument-2-Seite001.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/2180979/Dokument-2-Seite001.svg.zip)

### PR DESCRIPTION
**Pull request by hungerpirat**
This not only fixes #308 , it is supporting svg <use> tags in general. 
Therefore I added a small snap plugin unref.js, which does the dereferencing of the use tags during placement.
Besides of that, the commit c2d21ff does many improvements to working_area.js I discovered during debugging. Most  significant: check_sizes_and_placements() was called 3-6 times when placing (and removing!) an svg file. Now this happens only one time.

### CODE REVIEW

File: octoprint_mrbeam/static/js/working_area.js [hunk 1]
```diff
@@ -922,7 +921,7 @@ $(function(){
 
             var mb_meta = self._set_mb_attributes(newSvg);
 			newSvg.embed_gc(self.flipYMatrix(), self.gc_options(), mb_meta);
-
+			// self.check_sizes_and_placements(); // TODO?
```
Comment (andywerner) [inline octoprint_mrbeam/static/js/working_area.js:924]: remove line

File: octoprint_mrbeam/static/js/working_area.js [hunk 2]
```diff
@@ -1513,7 +1514,7 @@ $(function(){
 				var el = tip[i];
 				el.ftRemoveHandles();
 			}
-			self.check_sizes_and_placements();
+			//self.check_sizes_and_placements();
```
Comment (andywerner) [inline octoprint_mrbeam/static/js/working_area.js:1517]: remove line

**Review by andywerner — CHANGES_REQUESTED** [review]
remove two comments

**Review by andywerner — APPROVED** [review]
