### PR TITLE
Fixes #1267: Vectornator (generator info and bugs in handling SVGs)

### LINKED ISSUE #1267: SVGs from Vectornator are not handled correctly
We know this issue with SVGs from Vectornator (https://www.vectornator.io/)
which creates SVG paths which use a plus sign as separator between parameters. Snap.svg can not handle this.
[Archive 5.zip](https://github.com/mrbeam/MrBeamPlugin/files/6599282/Archive.5.zip)
Therefore if the path does not contain any whitespace nor comma but some plus signs, we replace these by commas.

### PR DESCRIPTION
**Pull request by andywerner**
Fixes #1267

### CODE REVIEW

**Comment by Gallore** [comment]
We have a fix: https://github.com/mrbeam/MrBeamPlugin/pull/1268
should go out with the next beta release

File: octoprint_mrbeam/static/js/matrix_oven.js [hunk 1]
```diff
@@ -208,10 +208,31 @@ Snap.plugin(function (Snap, Element, Paper, global) {
...
+        var arr_orig;
         var d = path_elem.attr("d");
         d = (d || "").trim();
-        var arr_orig;
-        arr = Snap.parsePathString(d);
+
+        // trying to catch and handle bug in Snap.svg
+        // We know this issue with SVGs from Vectornator (https://www.vectornator.io/)
+        // which creates SVG paths which use a plus sign as separator between parameters. Snap.svg can not handle this.
+        // Therefore if the path does not contain any whitespace nor comma but some plus signs, we replace these by commas.
```
Comment (hungerpirat) [inline octoprint_mrbeam/static/js/matrix_oven.js:218]: What about an example: "M129.122+146.728L491.004+152.024L491.004+179.68..." => "M129.122,146.728L491.004,152.024L491.004,179.68..."

**Review by hungerpirat — COMMENTED** [review]
example of the svg change could help understand why and what has been done to avoid the bug.

File: octoprint_mrbeam/static/js/matrix_oven.js (hunk 1 above)
Comment (andywerner) [reply octoprint_mrbeam/static/js/matrix_oven.js:218]: done

File: octoprint_mrbeam/static/js/matrix_oven.js [hunk 2]
```diff
@@ -208,10 +208,32 @@ Snap.plugin(function (Snap, Element, Paper, global) {
...
+            arr = Snap.parsePathString(d);
+            console.warn(
+                "matrix_oven: Handled potential Snap.svg bug: Path contains no whitespace and no comma but plus signs. " +
+                    "After replacing all '+' by ',' the new path is " +
+                    arr.length +
+                    "\n\noriginal d:\n" +
+                    dOld +
+                    "\n\nfixed d:\n" +
+                    d
+            );
```
Comment (amrsoll) [inline octoprint_mrbeam/static/js/matrix_oven.js:232]: It is not worth it to put the dOld string in the console. You are potentially making a huge dump and it can affect performance for no reason when not in dev mode.

I suggest to just replace the `+` into `,` in place for `d` and have `arr = Snap.parsePathString(d);` outside the `if` statement and simply have a single line warning when replacing the `+` characters.

**Review by amrsoll — CHANGES_REQUESTED** [review]
See comment

File: octoprint_mrbeam/static/js/matrix_oven.js (hunk 2 above)
Comment (andywerner) [reply octoprint_mrbeam/static/js/matrix_oven.js:232]: In the beginning I want this output to be available from the customers. (Remember, we send the output to the backend.) However, if there's too much load on the system, it'll drop the call to the backend.
